#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop sonos.service >/dev/null
  systemctl disable sonos.service || true
  rm -r /var/log/thingsplex/sonos/ || true
  rm -r /opt/thingsplex/sonos/data || true
fi